### ISSUE TITLE
Need help testing

### ISSUE THREAD

**Issue by RnbWd** [vitaly-t/gulp-decomment#3]
Hi, I ran into issues testing all the API methods in [gulp-strip-comments](https://github.com/RnbWd/gulp-strip-comments), and I was wondering if you could help me figure it out or just copy/paste the tests from this repo, which has much better coverage.

**Comment by vitaly-t** [comment]
What kind of problem are you talking about? In this library I have 100% test coverage. How can I help you?

To copy'n paste the tests, you would also need to copy'n paste the implementation + dependencies ;) so essentially, everything.

Perhaps the best way is to see if the problem is there when using this library...

**Comment by vitaly-t** [comment]
Sorry, I wrote the previous one after a night out, and wasn't thinking right :) Clearly, you just want to take all my tests, which would require the dependencies also. I will do a PR for you ;)

**Comment by RnbWd** [comment]
no worries! yeah I just noticed the tests here have much better coverage
and I was having some trouble testing a few of the methods (although I'm
confident everythings should work considering all the test coverage here)
